### ISSUE TITLE
Error fetching data?

### ISSUE THREAD

**Issue by MySupersuit** [Ardakilic/Recommendify#5]
I know last fm changed a few things but is this working anymore?

Just want to make playlists from the Play your library/mix/recommendations so will have a look at the code anyway

**Comment by Ardakilic** [comment]
Hey there, 

Last time I've checked, sadly, last.fm blocked providing the playlist with Spotify songs on client side, so, for the time being, this makes this repository useless. I couldn't make time to investigate further, but any ideas would be appreciate to take action.

**Comment by Ardakilic** [comment]
Some ideas:

The code could be written from scratch, and the playlist file could be fetched at backend. However, needs a headless browser something like puppeteer to scrape this data, and this also needs last.fm credentials to be stored somewhere. As a result, this won't be a pure client-side solution. 

An alternative is to make users get the playlist JSON file paste into a textarea field for the script to parse and make the playlist, but this would look quite ugly.

**Comment by Ardakilic** [comment]
First tries with puppeteer, success! 🎉 

![image](https://user-images.githubusercontent.com/2063957/58354478-43327180-7e7a-11e9-93c3-b22986d0a86f.png)

Sadly, if I decide to go with this route, the script cannot be a pure client-side solution anymore, so the user/hoster would need some kind of a server to host the code.

**Comment by Ardakilic** [comment]
There's a work in progress to fetch data from backend. All you need is to provide last.fm credentials, which is connected to a Premium Spotify account.

https://github.com/Ardakilic/Recommendify/tree/next

I'll try to deploy to a service when the work is done.

**Comment by Ardakilic** [comment]
OK, 

The codes are at master branch and ready to be used 🎉  I've just released a new major version:

https://github.com/Ardakilic/Recommendify/releases/tag/v2.0.0

For the time being, you can deploy and use yourself. It's quite straightforward (clone the codes, install dependencies, install puppeteer dependencies). However, when I deploy to Heroku, puppeteer cannot login to last.fm. I couldn't solve it. It works nicely on my local machines and two Debian servers I've tried. Possibly, last.fm bans Heroku Paas for authentication concerning the bot attacks. I couldn't solve this.

I'll try to find a server that puppeteer works nicely with last.fm.

**Comment by Ardakilic** [comment]
This issue can be considered as fixed, only thing remains is to find a server to host the codes. I'll track its progress elsewhere.

**Comment by Ardakilic** [comment]
I've released v2.0.1 and deployed to a server, you can access to the service at https://recommendify2.herokuapp.com
