### ISSUE TITLE
Error fetching your data. This may be due wrong username or api connection error.

### ISSUE THREAD

**Issue by guttitto** [Ardakilic/Recommendify#69]
Hello, so I keep receiving this error, even though I have a spotify premium account connected to my last fm account.
![image](https://user-images.githubusercontent.com/25709670/111096862-3daa8d80-851f-11eb-81b4-2d0ef92c7c52.png)

**Comment by Ardakilic** [comment]
Hello, apologies for the late reply, I have been sick and totally missed this issue.

Are you trying on the heroku instance or are you self-hosting this?

By the way, you can export from last.fm directly. Recently it has been added to Last.fm. This tool becomes somehow obsolete :)

![image](https://user-images.githubusercontent.com/2063957/113506668-e3fe1780-954e-11eb-87af-daaabefb45d3.png)

Just create a new playlist from last.fm, use "recommended" template or whatever you like, it'll be filled. Then you can directly export to Spotify.

![image](https://user-images.githubusercontent.com/2063957/113506659-d2b50b00-954e-11eb-8a26-b308b3d4a3c3.png)

According to your reply, I'll try to look for the underlying issue, but for the time being you can achieve this over last.fm directly.

**Comment by guttitto** [comment]
Thank you, i didn't know about the export playlist option
